---
apiVersion: v1
kind: Service
metadata:
  name: graphite
  namespace: monitoring
  labels:
    app: graphite
spec:
  type: NodePort
  ports:
    - port: 8000
      name: webui
      protocol: TCP
    - port: 2003
      name: carbon
      protocol: TCP
  selector:
    app: graphite
